### ISSUE TITLE
Unable to create new SelfServiceRegistrationFlow model from hash

### ISSUE THREAD

**Issue by znorris** [ory/kratos-client-ruby#4]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-client-ruby/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-client-ruby/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

A successful call results in error, see reproducing the bug. It has to do with converting the response key values (as hash) into the appropriate OpenAPI models. Debug this loop for answers https://github.com/ory/client-ruby/blob/master/lib/ory-client/models/ui_container.rb#L159-L171.

Workaround:
I'm able to request a hash of the response data rather than the model by specifying a debug option. I don't get to work with a class model but I think that will be okay at this time.

```ruby
flow_id = params[:flow]
opts = {
    :cookie => csrf_token,
    :debug_return_type => 'Object'
}

kratos_client = OryKratosClient::V0alpha2Api.new
data, status_code, headers = kratos_client.get_self_service_registration_flow_with_http_info(flow_id, opts) 
```

### Reproducing the bug

Make successful cloud API request with ory-kratos-client 0.8.0.alpha2

```ruby
flow_id = params[:flow]
opts = {
    :cookie => csrf_token,
}

kratos_client = OryKratosClient::V0alpha2Api.new
data, status_code, headers = kratos_client.get_self_service_registration_flow_with_http_info(flow_id, opts) 
```

Response body:
```json
{"id":"e90f14c4-9619-406d-8c8e-42e5740d2ef2","type":"browser","expires_at":"2021-11-22T19:12:37.047752Z","issued_at":"2021-11-22T18:12:37.047752Z","request_url":"http://beautiful-goodall-088evk4xui.projects.oryapis.com/self-service/registration/browser?isProxy=true","ui":{"action":"https://localhost:4000/.ory/api/kratos/public/self-service/registration?flow=e90f14c4-9619-406d-8c8e-42e5740d2ef2","method":"POST","nodes":[{"type":"input","group":"default","attributes":{"name":"csrf_token","type":"hidden","value":"faQU97TPaLlorzCkXQ37h+ZRXwVQTTApvh7HxjOQRNLRfdhbwLM7zmqNJgprh5PmuirZUrAiQ+YxrMtYz+F+rQ==","required":true,"disabled":false,"node_type":"input"},"messages":[],"meta":{}},{"type":"input","group":"password","attributes":{"name":"traits.email","type":"email","required":true,"disabled":false,"node_type":"input"},"messages":[],"meta":{"label":{"id":1070002,"text":"E-Mail","type":"info"}}},{"type":"input","group":"password","attributes":{"name":"password","type":"password","required":true,"disabled":false,"node_type":"input"},"messages":[],"meta":{"label":{"id":1070001,"text":"Password","type":"info"}}},{"type":"input","group":"password","attributes":{"name":"method","type":"submit","value":"password","disabled":false,"node_type":"input"},"messages":[],"meta":{"label":{"id":1040001,"text":"Sign up","type":"info","context":{}}}}]}}
```

### Relevant log output

Exception:
```ruby
NameError (uninitialized constant OryKratosClient::AnyType)
```

### Version

0.8.0.alpha2

### On which operating system are you observing this issue?

Ory Cloud

### In which environment are you deploying?

Ory Cloud

### Additional Context

Ory Proxy CLI v0.0.72

**Comment by aeneasr** [comment]
Hi there :) Thank you so much for the report! It looks like this could be a bug in the OpenAPI Generator? There's a new version released of it, unfortunately it had some regressions in Rust which produced uncompilable code, which is why we had to revert the update again. I found the following references:

- https://github.com/OpenAPITools/openapi-generator/issues/10190
- https://github.com/OpenAPITools/openapi-generator/pull/10192

If all goes well and 5.3.1 fixes the 5.3.0 regression for rust, we should be able to upgrade and thus resolve this issue. I'll keep it open in the meanwhile to track it for others :)
